### ISSUE TITLE
Generate featured images for posts

### ISSUE THREAD

**Issue by kalnode** [mbelchev/dummy-images#1]
Hey,

Is it possible to integrate this with posts, so every post (of a certain post type) would get a featured image generated which has post title on a solid color (or gradient) background.

Essentially I have no images for posts, and want to automatically generate them. This would be useful to populate social media cards, for instance.

**Comment by mbelchev** [comment]
Hi @TheMangoTrain,

Thank you for submitting this suggestion which is a good idea for extending the plugin's functionality.

In order to start the implementation of this feature, the plugin should expose the function for generating an image. It can be used in other plugins/themes which will be useful for the developers.

Once this function is ready to be used publicly (_outside the Dummy Images plugin_), it can be easily called in the proper WP hook for showing a featured image when it has to fall back to a default one.

Finally, a new Dashboard option, part of the Dummy Images, could be introduced via which the admins will be able to set a default image. However, this might not be 100% compatible with all WP themes in case the developer behind the theme hasn't used the proper way of calling a featured image or the theme has different featured image sizes.

The suggestion will be added to the ToDo list with future ideas. Feel free to add any follow-up comments around your suggestion. Thanks!
